Update ci-cd.yaml

diff --git a/.github/workflows/ci-cd.yaml b/.github/workflows/ci-cd.yaml
--- a/.github/workflows/ci-cd.yaml
+++ b/.github/workflows/ci-cd.yaml
@@ -17,142 +17,144 @@ jobs:
   deploy:
     runs-on: ubuntu-latest
     steps:
-      - name: Checkout
-        if: ${{ github.event.inputs.operation == 'deploy_default_feature' || github.event.inputs.operation == 'rollback_to_default_feature' || github.event.inputs.operation == 'deploy_new_feature' }}
-        uses: actions/checkout@v4
+      - name: TEST ENV VAR - GITHUB_REF
+        run: echo ${GITHUB_REF}
+        
+      - name: TEST ENV VAR - github.ref_name
+        run: echo ${{ github.ref_name }}        
 
-      - name: Login to Azure
-        if: ${{ github.event.inputs.operation == 'deploy_default_feature' || github.event.inputs.operation == 'rollback_to_default_feature' || github.event.inputs.operation == 'deploy_new_feature' }}
-        uses: azure/login@v1
-        with:
-          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}"}'
+      # - name: Login to Azure
+      #   if: ${{ github.event.inputs.operation == 'deploy_default_feature' || github.event.inputs.operation == 'rollback_to_default_feature' || github.event.inputs.operation == 'deploy_new_feature' }}
+      #   uses: azure/login@v1
+      #   with:
+      #     creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}"}'
 
-      - name: Login to Azure Container Registry
-        if: ${{ github.event.inputs.operation == 'deploy_default_feature' || github.event.inputs.operation == 'rollback_to_default_feature' || github.event.inputs.operation == 'deploy_new_feature' }}
-        run: az acr login --name ${{ secrets.ACR_REGISTRY }}
+      # - name: Login to Azure Container Registry
+      #   if: ${{ github.event.inputs.operation == 'deploy_default_feature' || github.event.inputs.operation == 'rollback_to_default_feature' || github.event.inputs.operation == 'deploy_new_feature' }}
+      #   run: az acr login --name ${{ secrets.ACR_REGISTRY }}
 
-      - name: Set Image Tag
-        if: ${{ github.event.inputs.operation == 'deploy_default_feature' || github.event.inputs.operation == 'deploy_new_feature' }}
-        id: set-image-tag
-        run: echo "IMAGE_TAG=$(echo $RANDOM)" >> $GITHUB_ENV
+      # - name: Set Image Tag
+      #   if: ${{ github.event.inputs.operation == 'deploy_default_feature' || github.event.inputs.operation == 'deploy_new_feature' }}
+      #   id: set-image-tag
+      #   run: echo "IMAGE_TAG=$(echo $RANDOM)" >> $GITHUB_ENV
 
-      - name: Build, Tag, and Push Image to ACR
-        if: ${{ github.event.inputs.operation == 'deploy_default_feature' || github.event.inputs.operation == 'deploy_new_feature' }}
-        env:
-          ACR_REPOSITORY: aks-app
-        run: |
-          docker build -t ${{ secrets.ACR_REGISTRY }}.azurecr.io/$ACR_REPOSITORY:$IMAGE_TAG .
-          docker push ${{ secrets.ACR_REGISTRY }}.azurecr.io/$ACR_REPOSITORY:$IMAGE_TAG
-          if [ "${{ github.event.inputs.operation }}" == "deploy_default_feature" ]; then
-            echo $IMAGE_TAG >> previous_image_tag.txt
-          fi
+      # - name: Build, Tag, and Push Image to ACR
+      #   if: ${{ github.event.inputs.operation == 'deploy_default_feature' || github.event.inputs.operation == 'deploy_new_feature' }}
+      #   env:
+      #     ACR_REPOSITORY: aks-app
+      #   run: |
+      #     docker build -t ${{ secrets.ACR_REGISTRY }}.azurecr.io/$ACR_REPOSITORY:$IMAGE_TAG .
+      #     docker push ${{ secrets.ACR_REGISTRY }}.azurecr.io/$ACR_REPOSITORY:$IMAGE_TAG
+      #     if [ "${{ github.event.inputs.operation }}" == "deploy_default_feature" ]; then
+      #       echo $IMAGE_TAG >> previous_image_tag.txt
+      #     fi
 
-      - name: Debug Image Tag File
-        if: ${{ github.event.inputs.operation == 'deploy_default_feature' }}
-        run: |
-          echo "Contents of previous_image_tag.txt:"
-          cat previous_image_tag.txt || echo "File not found"
+      # - name: Debug Image Tag File
+      #   if: ${{ github.event.inputs.operation == 'deploy_default_feature' }}
+      #   run: |
+      #     echo "Contents of previous_image_tag.txt:"
+      #     cat previous_image_tag.txt || echo "File not found"
 
-      - name: Deploy Default Feature of the Application
-        if: ${{ github.event.inputs.operation == 'deploy_default_feature' }}
-        env:
-          ACR_REPOSITORY: aks-app
-        run: |
-          az aks get-credentials --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --name ${{ secrets.AKS_CLUSTER_NAME }} --overwrite-existing
-          sed -i "s|<ACR_REGISTRY>.azurecr.io/<ACR_REPOSITORY>:<IMAGE_TAG>|${{ secrets.ACR_REGISTRY }}.azurecr.io/$ACR_REPOSITORY:$IMAGE_TAG|g" k8s/deployment.yaml
-          ACR_PASSWORD=$(az acr credential show --name myfeatureapp | jq -r .'passwords[0].value')
-          kubectl create secret docker-registry acr-secret \
-            --docker-server=${{ secrets.ACR_REGISTRY }}.azurecr.io \
-            --docker-username=${{ secrets.ACR_REGISTRY }} \
-            --docker-password=$ACR_PASSWORD          
-          kubectl apply -f k8s/deployment.yaml
-          kubectl apply -f k8s/service.yaml
-          kubectl rollout status deployment/aks-app
+      # - name: Deploy Default Feature of the Application
+      #   if: ${{ github.event.inputs.operation == 'deploy_default_feature' }}
+      #   env:
+      #     ACR_REPOSITORY: aks-app
+      #   run: |
+      #     az aks get-credentials --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --name ${{ secrets.AKS_CLUSTER_NAME }} --overwrite-existing
+      #     sed -i "s|<ACR_REGISTRY>.azurecr.io/<ACR_REPOSITORY>:<IMAGE_TAG>|${{ secrets.ACR_REGISTRY }}.azurecr.io/$ACR_REPOSITORY:$IMAGE_TAG|g" k8s/deployment.yaml
+      #     ACR_PASSWORD=$(az acr credential show --name myfeatureapp | jq -r .'passwords[0].value')
+      #     kubectl create secret docker-registry acr-secret \
+      #       --docker-server=${{ secrets.ACR_REGISTRY }}.azurecr.io \
+      #       --docker-username=${{ secrets.ACR_REGISTRY }} \
+      #       --docker-password=$ACR_PASSWORD          
+      #     kubectl apply -f k8s/deployment.yaml
+      #     kubectl apply -f k8s/service.yaml
+      #     kubectl rollout status deployment/aks-app
 
-      - name: Deploy New Feature of the Application
-        if: ${{ github.event.inputs.operation == 'deploy_new_feature' }}
-        env:
-          ACR_REPOSITORY: aks-app
-        run: |
-          az aks get-credentials --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --name ${{ secrets.AKS_CLUSTER_NAME }} --overwrite-existing
-          sed -i "s|<ACR_REGISTRY>.azurecr.io/<ACR_REPOSITORY>:<IMAGE_TAG>|${{ secrets.ACR_REGISTRY }}.azurecr.io/$ACR_REPOSITORY:$IMAGE_TAG|g" k8s/deployment.yaml
-          # Enable feature toggle for Customer B (set to true for new feature)
-          sed -i 's/value: "false"/value: "true"/g' k8s/deployment.yaml  
-          ACR_PASSWORD=$(az acr credential show --name myfeatureapp | jq -r .'passwords[0].value')
-          kubectl create secret docker-registry acr-secret \
-            --docker-server=${{ secrets.ACR_REGISTRY }}.azurecr.io \
-            --docker-username=${{ secrets.ACR_REGISTRY }} \
-            --docker-password=$ACR_PASSWORD                   
-          kubectl apply -f k8s/deployment.yaml
-          kubectl apply -f k8s/service.yaml
-          kubectl rollout status deployment/aks-app
+      # - name: Deploy New Feature of the Application
+      #   if: ${{ github.event.inputs.operation == 'deploy_new_feature' }}
+      #   env:
+      #     ACR_REPOSITORY: aks-app
+      #   run: |
+      #     az aks get-credentials --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --name ${{ secrets.AKS_CLUSTER_NAME }} --overwrite-existing
+      #     sed -i "s|<ACR_REGISTRY>.azurecr.io/<ACR_REPOSITORY>:<IMAGE_TAG>|${{ secrets.ACR_REGISTRY }}.azurecr.io/$ACR_REPOSITORY:$IMAGE_TAG|g" k8s/deployment.yaml
+      #     # Enable feature toggle for Customer B (set to true for new feature)
+      #     sed -i 's/value: "false"/value: "true"/g' k8s/deployment.yaml  
+      #     ACR_PASSWORD=$(az acr credential show --name myfeatureapp | jq -r .'passwords[0].value')
+      #     kubectl create secret docker-registry acr-secret \
+      #       --docker-server=${{ secrets.ACR_REGISTRY }}.azurecr.io \
+      #       --docker-username=${{ secrets.ACR_REGISTRY }} \
+      #       --docker-password=$ACR_PASSWORD                   
+      #     kubectl apply -f k8s/deployment.yaml
+      #     kubectl apply -f k8s/service.yaml
+      #     kubectl rollout status deployment/aks-app
 
-      - name: Store Image Tag for Rollback
-        if: ${{ github.event.inputs.operation == 'deploy_default_feature' }}
-        uses: actions/upload-artifact@v4
-        with:
-          name: image-tags
-          path: previous_image_tag.txt
-          retention-days: 7
+      # - name: Store Image Tag for Rollback
+      #   if: ${{ github.event.inputs.operation == 'deploy_default_feature' }}
+      #   uses: actions/upload-artifact@v4
+      #   with:
+      #     name: image-tags
+      #     path: previous_image_tag.txt
+      #     retention-days: 7
 
-      - name: 'Download artifact from latest build'
-        if: ${{ github.event.inputs.operation == 'deploy_new_feature' }}
-        uses: dawidd6/action-download-artifact@v6
-        with:
-          workflow: ci-cd.yaml
-          name: image-tags
-          path: downloaded-artifact
+      # - name: 'Download artifact from latest build'
+      #   if: ${{ github.event.inputs.operation == 'deploy_new_feature' }}
+      #   uses: dawidd6/action-download-artifact@v6
+      #   with:
+      #     workflow: ci-cd.yaml
+      #     name: image-tags
+      #     path: downloaded-artifact
 
-      - name: Store Image Tag to Pass on to Next Operation
-        if: ${{ github.event.inputs.operation == 'deploy_new_feature' }}
-        uses: actions/upload-artifact@v4
-        with:
-          name: image-tags
-          path: downloaded-artifact/previous_image_tag.txt
-          retention-days: 7
+      # - name: Store Image Tag to Pass on to Next Operation
+      #   if: ${{ github.event.inputs.operation == 'deploy_new_feature' }}
+      #   uses: actions/upload-artifact@v4
+      #   with:
+      #     name: image-tags
+      #     path: downloaded-artifact/previous_image_tag.txt
+      #     retention-days: 7
 
-      - name: 'Download artifact from latest build'
-        if: ${{ github.event.inputs.operation == 'rollback_to_default_feature' }}
-        uses: dawidd6/action-download-artifact@v6
-        with:
-          workflow: ci-cd.yaml
-          name: image-tags
-          path: downloaded-artifact
+      # - name: 'Download artifact from latest build'
+      #   if: ${{ github.event.inputs.operation == 'rollback_to_default_feature' }}
+      #   uses: dawidd6/action-download-artifact@v6
+      #   with:
+      #     workflow: ci-cd.yaml
+      #     name: image-tags
+      #     path: downloaded-artifact
 
-      - name: Verify Artifact Download
-        if: ${{ github.event.inputs.operation == 'rollback_to_default_feature' }}
-        run: |
-          if [ -f "downloaded-artifact/previous_image_tag.txt" ]; then
-            echo "Artifact downloaded successfully. Contents:"
-            cat downloaded-artifact/previous_image_tag.txt
-          else
-            echo "Error: Artifact 'image-tags' not found or download failed"
-            echo "Possible causes:"
-            echo "- Deploy workflow failed to upload artifact"
-            echo "- Artifact expired (retention period: 7 days)"
-            echo "- Incompatible artifact version"
-            exit 1
-          fi
+      # - name: Verify Artifact Download
+      #   if: ${{ github.event.inputs.operation == 'rollback_to_default_feature' }}
+      #   run: |
+      #     if [ -f "downloaded-artifact/previous_image_tag.txt" ]; then
+      #       echo "Artifact downloaded successfully. Contents:"
+      #       cat downloaded-artifact/previous_image_tag.txt
+      #     else
+      #       echo "Error: Artifact 'image-tags' not found or download failed"
+      #       echo "Possible causes:"
+      #       echo "- Deploy workflow failed to upload artifact"
+      #       echo "- Artifact expired (retention period: 7 days)"
+      #       echo "- Incompatible artifact version"
+      #       exit 1
+      #     fi
 
-      - name: Rollback to Previous/Default Feature
-        if: ${{ github.event.inputs.operation == 'rollback_to_default_feature' }}
-        env:
-          ACR_REPOSITORY: aks-app
-        run: |
-          PREVIOUS_IMAGE_TAG=$(head -n 1 downloaded-artifact/previous_image_tag.txt)
-          if [ -z "$PREVIOUS_IMAGE_TAG" ]; then
-            echo "Error: No previous image tag found in previous_image_tag.txt"
-            exit 1
-          fi        
-          az aks get-credentials --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --name ${{ secrets.AKS_CLUSTER_NAME }} --overwrite-existing
-          sed -i "s|<ACR_REGISTRY>.azurecr.io/<ACR_REPOSITORY>:<IMAGE_TAG>|${{ secrets.ACR_REGISTRY }}.azurecr.io/$ACR_REPOSITORY:$IMAGE_TAG|g" k8s/deployment.yaml
-          # Disable feature toggle for rollback
-          sed -i 's/value: "true"/value: "false"/g' k8s/deployment.yaml   
-          ACR_PASSWORD=$(az acr credential show --name myfeatureapp | jq -r .'passwords[0].value')
-          kubectl create secret docker-registry acr-secret \
-            --docker-server=${{ secrets.ACR_REGISTRY }}.azurecr.io \
-            --docker-username=${{ secrets.ACR_REGISTRY }} \
-            --docker-password=$ACR_PASSWORD                  
-          kubectl apply -f k8s/deployment.yaml
-          kubectl apply -f k8s/service.yaml
-          kubectl rollout status deployment/aks-app        
+      # - name: Rollback to Previous/Default Feature
+      #   if: ${{ github.event.inputs.operation == 'rollback_to_default_feature' }}
+      #   env:
+      #     ACR_REPOSITORY: aks-app
+      #   run: |
+      #     PREVIOUS_IMAGE_TAG=$(head -n 1 downloaded-artifact/previous_image_tag.txt)
+      #     if [ -z "$PREVIOUS_IMAGE_TAG" ]; then
+      #       echo "Error: No previous image tag found in previous_image_tag.txt"
+      #       exit 1
+      #     fi        
+      #     az aks get-credentials --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --name ${{ secrets.AKS_CLUSTER_NAME }} --overwrite-existing
+      #     sed -i "s|<ACR_REGISTRY>.azurecr.io/<ACR_REPOSITORY>:<IMAGE_TAG>|${{ secrets.ACR_REGISTRY }}.azurecr.io/$ACR_REPOSITORY:$IMAGE_TAG|g" k8s/deployment.yaml
+      #     # Disable feature toggle for rollback
+      #     sed -i 's/value: "true"/value: "false"/g' k8s/deployment.yaml   
+      #     ACR_PASSWORD=$(az acr credential show --name myfeatureapp | jq -r .'passwords[0].value')
+      #     kubectl create secret docker-registry acr-secret \
+      #       --docker-server=${{ secrets.ACR_REGISTRY }}.azurecr.io \
+      #       --docker-username=${{ secrets.ACR_REGISTRY }} \
+      #       --docker-password=$ACR_PASSWORD                  
+      #     kubectl apply -f k8s/deployment.yaml
+      #     kubectl apply -f k8s/service.yaml
+      #     kubectl rollout status deployment/aks-app        
